{{- if eq (int .Values.controllerManager.controlPlaneReplicas) 1 }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kube-controller-manager
  namespace: kube-system
  labels:
    tier: control-plane
    k8s-app: kube-controller-manager
spec:
  replicas: 1
  selector:
    matchLabels:
      tier: control-plane
      k8s-app: kube-controller-manager
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
  template:
    metadata:
      labels:
        tier: control-plane
        k8s-app: kube-controller-manager
      annotations:
        seccomp.security.alpha.kubernetes.io/pod: 'docker/default'
        # Automatically rolls update when secret changes.
        checksum/secret: {{ include (print $.Template.BasePath "/kube-controller-manager-secret.yaml") . | sha256sum }}
    spec:
{{- template "controller-manager-containers" . }}
{{- end }}
